// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: prompt-test-record.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPromptTestRecord = `-- name: CreatePromptTestRecord :one

INSERT INTO prompt_test_record (name,
                                variable_values,
                                response,
                                prompt_request_record_id)
values ($1, $2, $3, $4)
RETURNING id, name, variable_values, response, created_at, prompt_request_record_id
`

type CreatePromptTestRecordParams struct {
	Name                  string      `json:"name"`
	VariableValues        []byte      `json:"variableValues"`
	Response              string      `json:"response"`
	PromptRequestRecordID pgtype.UUID `json:"promptRequestRecordId"`
}

// -- prompt test record
func (q *Queries) CreatePromptTestRecord(ctx context.Context, arg CreatePromptTestRecordParams) (PromptTestRecord, error) {
	row := q.db.QueryRow(ctx, createPromptTestRecord,
		arg.Name,
		arg.VariableValues,
		arg.Response,
		arg.PromptRequestRecordID,
	)
	var i PromptTestRecord
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VariableValues,
		&i.Response,
		&i.CreatedAt,
		&i.PromptRequestRecordID,
	)
	return i, err
}
