// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one

INSERT INTO token (application_id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, deleted_at, application_id
`

type CreateTokenParams struct {
	ApplicationID pgtype.UUID `json:"applicationId"`
	Name          string      `json:"name"`
}

// -- token
func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken, arg.ApplicationID, arg.Name)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.ApplicationID,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :exec
UPDATE token
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteToken, id)
	return err
}

const retrieveTokens = `-- name: RetrieveTokens :many
SELECT
    id,
    name,
    created_at
FROM token
WHERE
    application_id = $1
    AND deleted_at IS NULL
ORDER BY created_at
`

type RetrieveTokensRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) RetrieveTokens(ctx context.Context, applicationID pgtype.UUID) ([]RetrieveTokensRow, error) {
	rows, err := q.db.Query(ctx, retrieveTokens, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrieveTokensRow
	for rows.Next() {
		var i RetrieveTokensRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
