version = 1

exclude_patterns = [
    "**/*.js",
    "shared/go/db/*.sql.go",
    "shared/go/db/models.go",
    "shared/go/db/db.go",
    "**/node_modules/**",
    "build/**",
    "dist/**",
    "e2e/**",
    "gen/**",
    "node_modules/**",
]

test_patterns = [
    "**/*_test.go",
    "**/__mocks__/**",
    "**/main.go",
    "**/mocks.*",
    "**/mocks/**",
    "**/test*/**",
    "**/tests/**",
    "**/testutils/**",
    "**/vitest.*",
    "vitest.*",
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "kotlin"

[analyzers.meta]
runtime_version = "1.8"
language_version = "1.9"

[[analyzers]]
name = "java"

[analyzers.meta]
runtime_version = "17"

[[analyzers]]
name = "javascript"

[analyzers.meta]
plugins = ["react"]
environment = [
    "nodejs",
    "browser",
    "vitest"
]

[[analyzers]]
name = "go"

[analyzers.meta]
import_root = "github.com/basemind-ai/monorepo"
