version = 1

exclude_patterns = [
    "gen/**",
    "e2e/**",
    "sdks/android/test-app/**",
    "**/node_modules/",
    "js/**/*.js"
]

test_patterns = [
    "**/*_test.go",
    "**/test/**",
    "**/tests/**",
]

[[analyzers]]
name = "kotlin"

[analyzers.meta]
runtime_version = "1.8"
language_version = "1.9"

[[analyzers]]
name = "java"

[analyzers.meta]
runtime_version = "17"

[[analyzers]]
name = "javascript"

[analyzers.meta]
plugins = ["react"]
environment = [
    "nodejs",
    "browser",
    "vitest"
]

[[analyzers]]
name = "go"

[analyzers.meta]
import_root = "github.com/basemind-ai/monorepo"
