run:
    go: '1.21'
linters-settings:
    govet:
        check-shadowing: true
linters:
    enable:
        - bidichk
        - durationcheck
        - errcheck
        - errorlint
        - exportloopref
        - goconst
        - gocritic
        - godot
        - godox
        - goheader
        - gomodguard
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - nolintlint
        - predeclared
        - sqlclosecheck
        - staticcheck
        - tenv
        - testpackage
        - typecheck
        - unconvert
        - unparam
        - unused
        - wastedassign
        - whitespace
issues:
    fix: true
