default_stages: [commit]
repos:
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: 'v9.5.0'
      hooks:
          - id: commitlint
            stages: [commit-msg]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v4.4.0'
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.9.0
      hooks:
          - id: shellcheck
            exclude: 'gradle*'
    - repo: https://github.com/hadolint/hadolint
      rev: v2.12.1-beta
      hooks:
          - id: hadolint-docker
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v3.0.3'
      hooks:
          - id: prettier
            exclude: 'go.mod|gen/ts'
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v8.50.0'
      hooks:
          - id: eslint
            files: \.tsx?$
            types: [file]
            exclude: 'gen/ts'
    - repo: https://github.com/golangci/golangci-lint
      rev: 'v1.54.2'
      hooks:
          - id: golangci-lint
            args: ['--timeout', '3m0s']
            exclude: 'gen/go'
    - repo: https://github.com/bufbuild/buf
      rev: v1.26.1
      hooks:
          - id: buf-format
          - id: buf-lint
    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 2.3.2
      hooks:
          - id: sqlfluff-lint
            exclude: 'sql/migrations'
            args: ['--dialect', 'postgres']
          - id: sqlfluff-fix
            exclude: 'sql/migrations'
            args: ['--dialect', 'postgres']
    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: 'v2.10.0'
      hooks:
          - id: pretty-format-java
            args: [--autofix]
            exclude: 'gen/kt'
          - id: pretty-format-kotlin
            args: [--autofix]
            exclude: 'gen/kt'
    - repo: local
      hooks:
          - id: detekt
            name: detekt
            description: Runs `detekt` on modified .kt files.
            language: script
            entry: .bin/detekt.sh
            files: \.kt
            exclude: 'gen/kt'
