default_stages: [commit]
repos:
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: 'v9.5.0'
      hooks:
          - id: commitlint
            stages: [commit-msg]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v4.5.0'
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: '.idea/modules'
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.9.0
      hooks:
          - id: shellcheck
            exclude: 'gradle*'
    - repo: https://github.com/hadolint/hadolint
      rev: v2.12.1-beta
      hooks:
          - id: hadolint-docker
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v3.0.3'
      hooks:
          - id: prettier
            exclude: 'go.mod|gen/ts|.idea/modules'
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v8.51.0'
      hooks:
          - id: eslint
            files: \.tsx?$
            types: [file]
            args: [--fix]
            exclude: 'gen/ts'
    - repo: https://github.com/golangci/golangci-lint
      rev: 'v1.54.2'
      hooks:
          - id: golangci-lint
            args: ['--timeout', '3m0s']
            exclude: 'gen/go'
    - repo: https://github.com/segmentio/golines
      rev: 'v0.11.0'
      hooks:
          - id: golines
    - repo: https://github.com/bufbuild/buf
      rev: v1.27.1
      hooks:
          - id: buf-format
          - id: buf-lint
    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 2.3.4
      hooks:
          - id: sqlfluff-fix
            exclude: 'sql/migrations'
