version: '3'

tasks:
    # repository management
    install-pre-commit:
        cmds:
            - |
                if command -v brew &> /dev/null; then
                    brew install pre-commit
                else
                    pip install pre-commit
                fi
        status:
            - command -v pre-commit &> /dev/null || exit 0
    setup:
        cmds:
            - task: install-pre-commit
            - pre-commit install && pre-commit install --hook-type commit-msg
            - pnpm install --frozen-lockfile
            - go mod download
    update:
        cmds:
            - pnpm update -r --latest
            - go mod tidy && go get -u ./... &> /dev/null
            - pre-commit autoupdate
    # database
    db-up:
        cmds:
            - docker compose stop && docker compose up db --detach
    apply-migrations:
        cmds:
            - task: db-up
            - sleep 2
            - atlas migrate apply --dir "file://sql/migrations" --url "postgresql://basemind:basemind@localhost:5432/basemind?search_path=public&sslmode=disable"
    create-migration:
        cmds:
            - task: db-up
            - sleep 2
            - atlas migrate diff {{.CLI_ARGS}} --dir "file://sql/migrations" --to "file://sql/schema.sql" --dev-url "postgresql://basemind:basemind@localhost:5432/basemind?search_path=public&sslmode=disable"
