version: '3'

includes:
    win: ./Taskfile_windows.yaml
tasks:
    # repository management
    install-pre-commit:
        cmds:
            - |
                if command -v brew &> /dev/null; then
                    brew install pre-commit
                else
                    pip install pre-commit
                fi
        status:
            - command -v pre-commit &> /dev/null || exit 0
    deps:setup:
        desc: Setup the project dependencies
        cmds:
            - task: install-pre-commit
            - pre-commit install && pre-commit install --hook-type commit-msg
            - pnpm install --frozen-lockfile
            - go mod download
    deps:update:
        desc: Update the project dependencies
        cmds:
            - pnpm update -r --latest
            - go mod tidy && go get -u ./... &> /dev/null
            - pre-commit autoupdate
    lint:
        desc: Lint the project
        cmds:
            - pre-commit run --all-files
    # database
    db:up:
        desc: Bring up the local database
        cmds:
            - docker compose stop && docker compose up db --detach
    db:down:
        desc: Tear down the local database
        cmds:
            - docker compose down db
    migrations:apply:
        desc: Apply the migrations to the local database
        cmds:
            - task: db-up
            - sleep 2
            - atlas migrate apply --dir "file://sql/migrations" --url "postgresql://basemind:basemind@localhost:5432/basemind?search_path=public&sslmode=disable"
    migrations:create:
        desc: Create a new migration
        cmds:
            - task: db-up
            - sleep 2
            - atlas migrate diff {{.CLI_ARGS}} --dir "file://sql/migrations" --to "file://sql/schema.sql" --dev-url "postgresql://basemind:basemind@localhost:5432/basemind?search_path=public&sslmode=disable"
