on:
    workflow_call:
        inputs:
            SERVICE_NAME:
                required: true
                type: string
            DOCKERFILE_PATH:
                required: true
                type: string
            BUILD_ARGS:
                required: true
                type: string
            GCP_PROJECT_ID:
                required: true
                type: string
            GCP_OIDC_PROVIDER_NAME:
                required: true
                type: string
            GCP_PROJECT_NUMBER:
                required: true
                type: string
            GCP_SERVICE_ACCOUNT_NAME:
                required: true
                type: string
            GCP_WORKLOAD_IDENTITY_POOL:
                required: true
                type: string
            GCP_REGION:
                required: true
                type: string
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
            - name: Authenticate to Google Cloud
              id: auth
              uses: google-github-actions/auth@v1
              with:
                  token_format: access_token
                  workload_identity_provider: projects/${{inputs.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{inputs.GCP_WORKLOAD_IDENTITY_POOL}}/providers/${{inputs.GCP_OIDC_PROVIDER_NAME}}
                  service_account: ${{inputs.GCP_SERVICE_ACCOUNT_NAME}}@${{inputs.GCP_PROJECT_ID}}.iam.gserviceaccount.com
            - name: Login to Artifact Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{inputs.GCP_REGION}}-docker.pkg.dev
                  username: oauth2accesstoken
                  password: ${{ steps.auth.outputs.access_token }}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker BuildX
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  context: .
                  file: ./docker/Dockerfile.go-services
                  build-args: ${{input.BUILD_ARGS}}
                  tags: |
                      ${{inputs.GCP_REGION}}-docker.pkg.dev/${{inputs.GCP_PROJECT_ID}}/basemind/${{inputs.SERVICE_NAME}}:latest
                      ${{inputs.GCP_REGION}}-docker.pkg.dev/${{inputs.GCP_PROJECT_ID}}/basemind/${{inputs.SERVICE_NAME}}:${{github.sha}}
