// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway/v1/gateway.proto

package com.basemind.client.grpc;

public final class Gateway {
  private Gateway() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
