// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway/v1/gateway.proto

package com.basemind.client.grpc;

public interface PromptResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gateway.v1.PromptResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * Number of tokens used for the prompt
   * </pre>
   *
   * <code>uint32 prompt_tokens = 2 [json_name = "promptTokens"];</code>
   * @return The promptTokens.
   */
  int getPromptTokens();
}
