// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway/v1/gateway.proto

package com.basemind.client.grpc;

/**
 * <pre>
 * A Prompt Response Message
 * </pre>
 *
 * Protobuf type {@code gateway.v1.PromptResponse}
 */
public  final class PromptResponse extends
    com.google.protobuf.GeneratedMessageLite<
        PromptResponse, PromptResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:gateway.v1.PromptResponse)
    PromptResponseOrBuilder {
  private PromptResponse() {
    content_ = "";
  }
  public static final int CONTENT_FIELD_NUMBER = 1;
  private java.lang.String content_;
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    return content_;
  }
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(content_);
  }
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @param value The content to set.
   */
  private void setContent(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    content_ = value;
  }
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   */
  private void clearContent() {

    content_ = getDefaultInstance().getContent();
  }
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @param value The bytes for content to set.
   */
  private void setContentBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    content_ = value.toStringUtf8();

  }

  public static final int PROMPT_TOKENS_FIELD_NUMBER = 2;
  private int promptTokens_;
  /**
   * <pre>
   * Number of tokens used for the prompt
   * </pre>
   *
   * <code>uint32 prompt_tokens = 2 [json_name = "promptTokens"];</code>
   * @return The promptTokens.
   */
  @java.lang.Override
  public int getPromptTokens() {
    return promptTokens_;
  }
  /**
   * <pre>
   * Number of tokens used for the prompt
   * </pre>
   *
   * <code>uint32 prompt_tokens = 2 [json_name = "promptTokens"];</code>
   * @param value The promptTokens to set.
   */
  private void setPromptTokens(int value) {

    promptTokens_ = value;
  }
  /**
   * <pre>
   * Number of tokens used for the prompt
   * </pre>
   *
   * <code>uint32 prompt_tokens = 2 [json_name = "promptTokens"];</code>
   */
  private void clearPromptTokens() {

    promptTokens_ = 0;
  }

  public static com.basemind.client.grpc.PromptResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.basemind.client.grpc.PromptResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.basemind.client.grpc.PromptResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.basemind.client.grpc.PromptResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.basemind.client.grpc.PromptResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.basemind.client.grpc.PromptResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.basemind.client.grpc.PromptResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.basemind.client.grpc.PromptResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.basemind.client.grpc.PromptResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.basemind.client.grpc.PromptResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.basemind.client.grpc.PromptResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.basemind.client.grpc.PromptResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.basemind.client.grpc.PromptResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A Prompt Response Message
   * </pre>
   *
   * Protobuf type {@code gateway.v1.PromptResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.basemind.client.grpc.PromptResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:gateway.v1.PromptResponse)
      com.basemind.client.grpc.PromptResponseOrBuilder {
    // Construct using com.basemind.client.grpc.PromptResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Prompt Content
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      return instance.getContent();
    }
    /**
     * <pre>
     * Prompt Content
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      return instance.getContentBytes();
    }
    /**
     * <pre>
     * Prompt Content
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      copyOnWrite();
      instance.setContent(value);
      return this;
    }
    /**
     * <pre>
     * Prompt Content
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      copyOnWrite();
      instance.clearContent();
      return this;
    }
    /**
     * <pre>
     * Prompt Content
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setContentBytes(value);
      return this;
    }

    /**
     * <pre>
     * Number of tokens used for the prompt
     * </pre>
     *
     * <code>uint32 prompt_tokens = 2 [json_name = "promptTokens"];</code>
     * @return The promptTokens.
     */
    @java.lang.Override
    public int getPromptTokens() {
      return instance.getPromptTokens();
    }
    /**
     * <pre>
     * Number of tokens used for the prompt
     * </pre>
     *
     * <code>uint32 prompt_tokens = 2 [json_name = "promptTokens"];</code>
     * @param value The promptTokens to set.
     * @return This builder for chaining.
     */
    public Builder setPromptTokens(int value) {
      copyOnWrite();
      instance.setPromptTokens(value);
      return this;
    }
    /**
     * <pre>
     * Number of tokens used for the prompt
     * </pre>
     *
     * <code>uint32 prompt_tokens = 2 [json_name = "promptTokens"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPromptTokens() {
      copyOnWrite();
      instance.clearPromptTokens();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:gateway.v1.PromptResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.basemind.client.grpc.PromptResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "content_",
            "promptTokens_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u000b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.basemind.client.grpc.PromptResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.basemind.client.grpc.PromptResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.basemind.client.grpc.PromptResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:gateway.v1.PromptResponse)
  private static final com.basemind.client.grpc.PromptResponse DEFAULT_INSTANCE;
  static {
    PromptResponse defaultInstance = new PromptResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PromptResponse.class, defaultInstance);
  }

  public static com.basemind.client.grpc.PromptResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PromptResponse> PARSER;

  public static com.google.protobuf.Parser<PromptResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
