// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway/v1/gateway.proto

package com.basemind.client.grpc;

public interface PromptConfigResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gateway.v1.PromptConfigResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The expected prompt variables
   * </pre>
   *
   * <code>repeated string expected_prompt_variables = 1 [json_name = "expectedPromptVariables"];</code>
   * @return A list containing the expectedPromptVariables.
   */
  java.util.List<java.lang.String>
      getExpectedPromptVariablesList();
  /**
   * <pre>
   * The expected prompt variables
   * </pre>
   *
   * <code>repeated string expected_prompt_variables = 1 [json_name = "expectedPromptVariables"];</code>
   * @return The count of expectedPromptVariables.
   */
  int getExpectedPromptVariablesCount();
  /**
   * <pre>
   * The expected prompt variables
   * </pre>
   *
   * <code>repeated string expected_prompt_variables = 1 [json_name = "expectedPromptVariables"];</code>
   * @param index The index of the element to return.
   * @return The expectedPromptVariables at the given index.
   */
  java.lang.String getExpectedPromptVariables(int index);
  /**
   * <pre>
   * The expected prompt variables
   * </pre>
   *
   * <code>repeated string expected_prompt_variables = 1 [json_name = "expectedPromptVariables"];</code>
   * @param index The index of the element to return.
   * @return The expectedPromptVariables at the given index.
   */
  com.google.protobuf.ByteString
      getExpectedPromptVariablesBytes(int index);
}
