// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway/v1/gateway.proto

package com.basemind.client.grpc;

public interface PromptConfigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gateway.v1.PromptConfigRequest)
    com.google.protobuf.MessageLiteOrBuilder {
}
