// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway/v1/gateway.proto

package com.basemind.client.grpc;

/**
 * <pre>
 * An Streaming Prompt Response Message
 * </pre>
 *
 * Protobuf type {@code gateway.v1.StreamingPromptResponse}
 */
public  final class StreamingPromptResponse extends
    com.google.protobuf.GeneratedMessageLite<
        StreamingPromptResponse, StreamingPromptResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:gateway.v1.StreamingPromptResponse)
    StreamingPromptResponseOrBuilder {
  private StreamingPromptResponse() {
    content_ = "";
    finishReason_ = "";
  }
  private int bitField0_;
  public static final int CONTENT_FIELD_NUMBER = 1;
  private java.lang.String content_;
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    return content_;
  }
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(content_);
  }
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @param value The content to set.
   */
  private void setContent(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    content_ = value;
  }
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   */
  private void clearContent() {

    content_ = getDefaultInstance().getContent();
  }
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @param value The bytes for content to set.
   */
  private void setContentBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    content_ = value.toStringUtf8();

  }

  public static final int FINISH_REASON_FIELD_NUMBER = 2;
  private java.lang.String finishReason_;
  /**
   * <pre>
   * Finish reason, if this is the last message
   * </pre>
   *
   * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
   * @return Whether the finishReason field is set.
   */
  @java.lang.Override
  public boolean hasFinishReason() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Finish reason, if this is the last message
   * </pre>
   *
   * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
   * @return The finishReason.
   */
  @java.lang.Override
  public java.lang.String getFinishReason() {
    return finishReason_;
  }
  /**
   * <pre>
   * Finish reason, if this is the last message
   * </pre>
   *
   * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
   * @return The bytes for finishReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFinishReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(finishReason_);
  }
  /**
   * <pre>
   * Finish reason, if this is the last message
   * </pre>
   *
   * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
   * @param value The finishReason to set.
   */
  private void setFinishReason(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    finishReason_ = value;
  }
  /**
   * <pre>
   * Finish reason, if this is the last message
   * </pre>
   *
   * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
   */
  private void clearFinishReason() {
    bitField0_ = (bitField0_ & ~0x00000001);
    finishReason_ = getDefaultInstance().getFinishReason();
  }
  /**
   * <pre>
   * Finish reason, if this is the last message
   * </pre>
   *
   * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
   * @param value The bytes for finishReason to set.
   */
  private void setFinishReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    finishReason_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int PROMPT_TOKENS_FIELD_NUMBER = 3;
  private int promptTokens_;
  /**
   * <pre>
   * Number of tokens used for the prompt, given when the stream ends
   * </pre>
   *
   * <code>optional uint32 prompt_tokens = 3 [json_name = "promptTokens"];</code>
   * @return Whether the promptTokens field is set.
   */
  @java.lang.Override
  public boolean hasPromptTokens() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Number of tokens used for the prompt, given when the stream ends
   * </pre>
   *
   * <code>optional uint32 prompt_tokens = 3 [json_name = "promptTokens"];</code>
   * @return The promptTokens.
   */
  @java.lang.Override
  public int getPromptTokens() {
    return promptTokens_;
  }
  /**
   * <pre>
   * Number of tokens used for the prompt, given when the stream ends
   * </pre>
   *
   * <code>optional uint32 prompt_tokens = 3 [json_name = "promptTokens"];</code>
   * @param value The promptTokens to set.
   */
  private void setPromptTokens(int value) {
    bitField0_ |= 0x00000002;
    promptTokens_ = value;
  }
  /**
   * <pre>
   * Number of tokens used for the prompt, given when the stream ends
   * </pre>
   *
   * <code>optional uint32 prompt_tokens = 3 [json_name = "promptTokens"];</code>
   */
  private void clearPromptTokens() {
    bitField0_ = (bitField0_ & ~0x00000002);
    promptTokens_ = 0;
  }

  public static com.basemind.client.grpc.StreamingPromptResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.basemind.client.grpc.StreamingPromptResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.basemind.client.grpc.StreamingPromptResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.basemind.client.grpc.StreamingPromptResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.basemind.client.grpc.StreamingPromptResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.basemind.client.grpc.StreamingPromptResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.basemind.client.grpc.StreamingPromptResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.basemind.client.grpc.StreamingPromptResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.basemind.client.grpc.StreamingPromptResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.basemind.client.grpc.StreamingPromptResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.basemind.client.grpc.StreamingPromptResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.basemind.client.grpc.StreamingPromptResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.basemind.client.grpc.StreamingPromptResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * An Streaming Prompt Response Message
   * </pre>
   *
   * Protobuf type {@code gateway.v1.StreamingPromptResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.basemind.client.grpc.StreamingPromptResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:gateway.v1.StreamingPromptResponse)
      com.basemind.client.grpc.StreamingPromptResponseOrBuilder {
    // Construct using com.basemind.client.grpc.StreamingPromptResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Prompt Content
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      return instance.getContent();
    }
    /**
     * <pre>
     * Prompt Content
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      return instance.getContentBytes();
    }
    /**
     * <pre>
     * Prompt Content
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      copyOnWrite();
      instance.setContent(value);
      return this;
    }
    /**
     * <pre>
     * Prompt Content
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      copyOnWrite();
      instance.clearContent();
      return this;
    }
    /**
     * <pre>
     * Prompt Content
     * </pre>
     *
     * <code>string content = 1 [json_name = "content"];</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setContentBytes(value);
      return this;
    }

    /**
     * <pre>
     * Finish reason, if this is the last message
     * </pre>
     *
     * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
     * @return Whether the finishReason field is set.
     */
    @java.lang.Override
    public boolean hasFinishReason() {
      return instance.hasFinishReason();
    }
    /**
     * <pre>
     * Finish reason, if this is the last message
     * </pre>
     *
     * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
     * @return The finishReason.
     */
    @java.lang.Override
    public java.lang.String getFinishReason() {
      return instance.getFinishReason();
    }
    /**
     * <pre>
     * Finish reason, if this is the last message
     * </pre>
     *
     * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
     * @return The bytes for finishReason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFinishReasonBytes() {
      return instance.getFinishReasonBytes();
    }
    /**
     * <pre>
     * Finish reason, if this is the last message
     * </pre>
     *
     * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
     * @param value The finishReason to set.
     * @return This builder for chaining.
     */
    public Builder setFinishReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setFinishReason(value);
      return this;
    }
    /**
     * <pre>
     * Finish reason, if this is the last message
     * </pre>
     *
     * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFinishReason() {
      copyOnWrite();
      instance.clearFinishReason();
      return this;
    }
    /**
     * <pre>
     * Finish reason, if this is the last message
     * </pre>
     *
     * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
     * @param value The bytes for finishReason to set.
     * @return This builder for chaining.
     */
    public Builder setFinishReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFinishReasonBytes(value);
      return this;
    }

    /**
     * <pre>
     * Number of tokens used for the prompt, given when the stream ends
     * </pre>
     *
     * <code>optional uint32 prompt_tokens = 3 [json_name = "promptTokens"];</code>
     * @return Whether the promptTokens field is set.
     */
    @java.lang.Override
    public boolean hasPromptTokens() {
      return instance.hasPromptTokens();
    }
    /**
     * <pre>
     * Number of tokens used for the prompt, given when the stream ends
     * </pre>
     *
     * <code>optional uint32 prompt_tokens = 3 [json_name = "promptTokens"];</code>
     * @return The promptTokens.
     */
    @java.lang.Override
    public int getPromptTokens() {
      return instance.getPromptTokens();
    }
    /**
     * <pre>
     * Number of tokens used for the prompt, given when the stream ends
     * </pre>
     *
     * <code>optional uint32 prompt_tokens = 3 [json_name = "promptTokens"];</code>
     * @param value The promptTokens to set.
     * @return This builder for chaining.
     */
    public Builder setPromptTokens(int value) {
      copyOnWrite();
      instance.setPromptTokens(value);
      return this;
    }
    /**
     * <pre>
     * Number of tokens used for the prompt, given when the stream ends
     * </pre>
     *
     * <code>optional uint32 prompt_tokens = 3 [json_name = "promptTokens"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPromptTokens() {
      copyOnWrite();
      instance.clearPromptTokens();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:gateway.v1.StreamingPromptResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.basemind.client.grpc.StreamingPromptResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "content_",
            "finishReason_",
            "promptTokens_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u1208" +
              "\u0000\u0003\u100b\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.basemind.client.grpc.StreamingPromptResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.basemind.client.grpc.StreamingPromptResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.basemind.client.grpc.StreamingPromptResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:gateway.v1.StreamingPromptResponse)
  private static final com.basemind.client.grpc.StreamingPromptResponse DEFAULT_INSTANCE;
  static {
    StreamingPromptResponse defaultInstance = new StreamingPromptResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      StreamingPromptResponse.class, defaultInstance);
  }

  public static com.basemind.client.grpc.StreamingPromptResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<StreamingPromptResponse> PARSER;

  public static com.google.protobuf.Parser<StreamingPromptResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
