// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway/v1/gateway.proto

package com.basemind.client.grpc;

public interface StreamingPromptResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gateway.v1.StreamingPromptResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * Prompt Content
   * </pre>
   *
   * <code>string content = 1 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * Finish reason, if this is the last message
   * </pre>
   *
   * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
   * @return Whether the finishReason field is set.
   */
  boolean hasFinishReason();
  /**
   * <pre>
   * Finish reason, if this is the last message
   * </pre>
   *
   * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
   * @return The finishReason.
   */
  java.lang.String getFinishReason();
  /**
   * <pre>
   * Finish reason, if this is the last message
   * </pre>
   *
   * <code>optional string finish_reason = 2 [json_name = "finishReason"];</code>
   * @return The bytes for finishReason.
   */
  com.google.protobuf.ByteString
      getFinishReasonBytes();

  /**
   * <pre>
   * Number of tokens used for the prompt, given when the stream ends
   * </pre>
   *
   * <code>optional uint32 prompt_tokens = 3 [json_name = "promptTokens"];</code>
   * @return Whether the promptTokens field is set.
   */
  boolean hasPromptTokens();
  /**
   * <pre>
   * Number of tokens used for the prompt, given when the stream ends
   * </pre>
   *
   * <code>optional uint32 prompt_tokens = 3 [json_name = "promptTokens"];</code>
   * @return The promptTokens.
   */
  int getPromptTokens();
}
