name: 'Build (API-Gateway)'
on:
    push:
        branches:
            - development
            - production
        paths:
            - 'gen/go/ptesting/**'
            - 'gen/go/gateway/**'
            - 'go.*'
            - 'services/api-gateway/**'
            - 'shared/go/**'
jobs:
    build:
        uses: ./.github/workflows/build.yaml
        secrets: inherit
        with:
            file_path: ./docker/Dockerfile.go-services
            service: api-gateway
            environment: ${{ github.ref_name }}
