name: 'Build'
on:
    workflow_call:
        inputs:
            timeout:
                required: false
                type: number
                default: 5
            service:
                required: true
                type: string
            file_path:
                required: true
                type: string
            gcp_project_number:
                required: true
                type: number
            gcp_project_id:
                required: true
                type: string
            gcp_region:
                required: true
                type: string
            gcp_service_account_name:
                required: true
                type: string
            gcp_workload_identity_pool:
                required: true
                type: string
            gcp_oidc_provider_name:
                required: true
                type: string
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: ${{ inputs.timeout }}
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
            - name: Authenticate to Google Cloud
              id: auth
              uses: google-github-actions/auth@v2
              with:
                  token_format: access_token
                  workload_identity_provider: projects/${{inputs.gcp_project_number}}/locations/global/workloadIdentityPools/${{inputs.gcp_workload_identity_pool}}/providers/${{inputs.gcp_oidc_provider_name}}
                  service_account: ${{inputs.gcp_service_account_name}}@${{inputs.gcp_project_id}}.iam.gserviceaccount.com
            - name: Login to Artifact Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{inputs.gcp_region}}-docker.pkg.dev
                  username: oauth2accesstoken
                  password: ${{ steps.auth.outputs.access_token }}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker BuildX
              uses: docker/setup-buildx-action@v3
            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  context: .
                  file: ${{inputs.file_path}}
                  build-args: |
                      BUILD_TARGET=${{inputs.service}}
                      SERVICE_NAME=${{inputs.service}}
                  tags: |
                      ${{inputs.gcp_region}}-docker.pkg.dev/${{inputs.gcp_project_id}}/basemind/${{inputs.service}}:latest
                      ${{inputs.gcp_region}}-docker.pkg.dev/${{inputs.gcp_project_id}}/basemind/${{inputs.service}}:${{github.sha}}
