name: 'Build'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
#  workflow_run:
#    branches:
#      - main
#    workflows:
#    - "Tests (Golang)"
#    types:
#      - completed
env:
    GCP_OIDC_PROVIDER_NAME: github-provider
    GCP_PROJECT_ID: basemind-ai-development
    GCP_PROJECT_NUMBER: 78794879644
    GCP_SERVICE_ACCOUNT_NAME: github-actions
    GCP_WORKLOAD_IDENTITY_POOL: dev-pool
    GCP_REGION: europe-west3
jobs:
    build:
        #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') # run only on tagged commits
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service:
                    - api-gateway
                    - dashboard-backend
        permissions:
            contents: 'read'
            id-token: 'write'
        steps:
            - id: checkout
              name: Checkout
              uses: actions/checkout@v4
            - name: Authenticate to Google Cloud
              id: auth
              uses: google-github-actions/auth@v1
              with:
                  token_format: access_token
                  workload_identity_provider: projects/${{env.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{env.GCP_WORKLOAD_IDENTITY_POOL}}/providers/${{env.GCP_OIDC_PROVIDER_NAME}}
                  service_account: ${{env.GCP_SERVICE_ACCOUNT_NAME}}@${{env.GCP_PROJECT_ID}}.iam.gserviceaccount.com
            - name: Login to Artifact Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{env.GCP_REGION}}-docker.pkg.dev
                  username: oauth2accesstoken
                  password: ${{ steps.auth.outputs.access_token }}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker BuildX
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  context: .
                  file: ./docker/Dockerfile.go-services
                  build-args: |
                      BUILD_TARGET=${{matrix.service}}
                  tags: |
                      ${{env.GCP_REGION}}-docker.pkg.dev/${{env.GCP_PROJECT_ID}}/basemind/${{matrix.service}}:latest
                      ${{env.GCP_REGION}}-docker.pkg.dev/${{env.GCP_PROJECT_ID}}/basemind/${{matrix.service}}:${{github.sha}}
