name: 'Build'
on:
    workflow_call:
        inputs:
            timeout:
                required: false
                type: number
                default: 5
            service:
                required: true
                type: string
            file_path:
                required: true
                type: string
            environment:
                required: true
                type: string
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: ${{ env.timeout }}
        environment: ${{ env.environment }}
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
            - name: Authenticate to Google Cloud
              id: auth
              uses: google-github-actions/auth@v2
              with:
                  token_format: access_token
                  workload_identity_provider: projects/${{env.gcp_project_number}}/locations/global/workloadIdentityPools/${{env.gcp_workload_identity_pool}}/providers/${{env.gcp_oidc_provider_name}}
                  service_account: ${{env.gcp_service_account_name}}@${{env.gcp_project_id}}.iam.gserviceaccount.com
            - name: Login to Artifact Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{env.gcp_region}}-docker.pkg.dev
                  username: oauth2accesstoken
                  password: ${{ steps.auth.outputs.access_token }}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker BuildX
              uses: docker/setup-buildx-action@v3
            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  context: .
                  file: ${{env.file_path}}
                  build-args: |
                      BUILD_TARGET=${{env.service}}
                      SERVICE_NAME=${{env.service}}
                  tags: |
                      ${{env.gcp_region}}-docker.pkg.dev/${{env.gcp_project_id}}/basemind/${{env.service}}:latest
                      ${{env.gcp_region}}-docker.pkg.dev/${{env.gcp_project_id}}/basemind/${{env.service}}:${{github.sha}}
