name: 'Build (OpenAI-Connector)'
on:
    push:
        branches:
            - development
            - production
        paths:
            - 'gen/ts/openai/**'
            - 'services/openai-connector/**'
            - 'shared/ts/**'
            - 'package.json'
jobs:
    build:
        uses: ./.github/actions/build.yaml
        secrets: inherit
        with:
            file_path: ./docker/Dockerfile.ts-services
            service: openai-connector
            environment: ${{ github.ref_name }}
