name: 'Build'
on:
    workflow_call:
        inputs:
            timeout:
                required: false
                type: number
                default: 5
            service:
                required: true
                type: string
            file_path:
                required: true
                type: string
            environment:
                required: true
                type: string
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: ${{ inputs.timeout }}
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
            - name: Authenticate to Google Cloud
              id: auth
              uses: google-github-actions/auth@v2
              with:
                  token_format: access_token
                  workload_identity_provider: projects/${{env.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{env.GCP_WORKLOAD_IDENTITY_POOL}}/providers/${{env.GCP_OIDC_PROVIDER_NAME}}
                  service_account: ${{env.GCP_SERVICE_ACCOUNT_NAME}}@${{env.GCP_PROJECT_ID}}.iam.gserviceaccount.com
            - name: Login to Artifact Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{env.GCP_REGION}}-docker.pkg.dev
                  username: oauth2accesstoken
                  password: ${{ steps.auth.outputs.access_token }}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker BuildX
              uses: docker/setup-buildx-action@v3
            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  context: .
                  file: ${{inputs.file_path}}
                  build-args: |
                      BUILD_TARGET=${{inputs.service}}
                      SERVICE_NAME=${{inputs.service}}
                  tags: |
                      ${{env.GCP_REGION}}-docker.pkg.dev/${{env.GCP_PROJECT_ID}}/basemind/${{inputs.service}}:latest
                      ${{env.GCP_REGION}}-docker.pkg.dev/${{env.GCP_PROJECT_ID}}/basemind/${{inputs.service}}:${{github.sha}}
