name: 'Validate'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Golang
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21'
            - name: Load cached Golang dependencies
              id: cached-go-dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: go-${{ inputs.go_version }}-v1.0-${{ hashFiles('**/go.sum') }}
            - name: Install Golang dependencies
              if: steps.cached-go-dependencies.outputs.cache-hit != 'true'
              shell: bash
              run: go get -v -t ./...

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Install pnpm
              uses: pnpm/action-setup@v2.4.0
              id: pnpm-install
              with:
                  version: 8
            - name: Setup pnpm cache
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              name: Load cached Node dependencies
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-store-
            - name: Install Node dependencies
              run: pnpm install -r

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'
            - name: Install Pre-Commit
              run: python -m pip install pre-commit && pre-commit install
            - name: Load cached Pre-Commit Dependencies
              id: cached-pre-commit-dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pre-commit/
                  key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
            - name: Execute Pre-Commit
              run: pre-commit run --show-diff-on-failure --color=always --all-files
