name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Load cached dependencies
        id: cached-go-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ inputs.go_version }}-v1.0-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.cached-go-dependencies.outputs.cache-hit != 'true'
        shell: bash
        run: go get -v -t ./...
  lint:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Load cached dependencies
        id: cached-go-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ inputs.go_version }}-v1.0-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.cached-go-dependencies.outputs.cache-hit != 'true'
        shell: bash
        run: go get -v -t ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        continue-on-error: true
        with:
          version: v1.53
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Load cached dependencies
        id: cached-go-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ inputs.go_version }}-v1.0-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.cached-go-dependencies.outputs.cache-hit != 'true'
        shell: bash
        run: go get -v -t ./...
      - name: Run Tests
        run: go test ./...
