name: Deploy (Frontend)
on:
    push:
        branches:
            - development
            - production
#        paths:
#            - 'frontend/src/**'
#            - 'shared/ts/**'
#            - 'package.json'
#            - '.github/workflows/deploy-frontend.yaml'
jobs:
    set_environment:
        runs-on: ubuntu-latest
        environment: ${{ github.ref_name }}
        steps:
            - name: Set Env Variables
              shell: bash
              run: |
                  echo "BACKEND_URL=${{ env.BACKEND_URL }}" >> $GITHUB_ENV
    deploy:
        permissions:
            checks: write
            contents: read
            pull-requests: write
        secrets: inherit
        uses: ./.github/workflows/deploy_firebase.yaml
        with:
            environment: ${{ github.ref_name }}
            is_preview: false
            backend_url: ${{ env.BACKEND_URL }}
