name: Deploy (Frontend)
on:
    push:
        branches:
            - development
            - production
        paths:
            - '.github/workflows/deploy-frontend.yaml'
            - 'frontend/src/**'
            - 'package.json'
            - 'shared/ts/**'
jobs:
    set_environment:
        runs-on: ubuntu-latest
        environment: ${{ github.ref_name }}
        outputs:
            BACKEND_URL: ${{ steps.set_env.outputs.BACKEND_URL }}
            GCP_PROJECT_ID: ${{ steps.set_env.outputs.GCP_PROJECT_ID }}
        steps:
            - name: Set Env Variables
              id: set_env
              shell: bash
              run: |
                  echo "BACKEND_URL=${{ vars.BACKEND_URL }}" >> "$GITHUB_OUTPUT"
                  echo "GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}" >> "$GITHUB_OUTPUT"
    deploy:
        needs: set_environment
        permissions:
            checks: write
            contents: read
            pull-requests: write
        secrets: inherit
        uses: ./.github/workflows/deploy_firebase.yaml
        with:
            backend_url: ${{needs.set_environment.outputs.BACKEND_URL}}
            environment: ${{ github.ref_name }}
            gcp_project_id: ${{needs.set_environment.outputs.GCP_PROJECT_ID}}
            is_preview: false
