name: Deploy (Frontend)
on:
    push:
        branches:
            - development
            - production
        paths:
            - 'frontend/src/**'
            - 'shared/ts/**'
            - 'package.json'
jobs:
    deploy:
        uses: ./.github/workflows/deploy_firebase.yaml
        secrets: inherit
        with:
            environment: ${{ github.ref_name }}
            is_preview: false
