name: Deploy (Frontend)
on:
    push:
        branches:
            - development
            - production
        paths:
            - 'frontend/src/**'
            - 'shared/ts/**'
            - 'package.json'
            - '.github/workflows/deploy-frontend.yaml'
jobs:
    deploy:
        uses: ./.github/workflows/deploy_firebase.yaml
        secrets: inherit
        permissions:
            checks: write
            contents: read
            pull-requests: write
        with:
            environment: ${{ github.ref_name }}
            is_preview: false
