name: Frontend Preview
on:
    pull_request:
        branches:
            - main
        paths:
            - 'frontend/src/**'
            - 'shared/ts/**'
            - 'package.json'
jobs:
    deploy:
        uses: ./.github/workflows/deploy_firebase.yaml
        secrets: inherit
        with:
            environment: ${{ github.ref_name }}
            is_preview: true
