name: Submit gradle dependency graph
on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2.8.1
              with:
                  dependency-graph: generate-and-submit
            - name: Run a build, generating the dependency graph snapshot which will be submitted
              run: ./gradlew build
