name: build
on:
    push:
        branches:
            - main

jobs:
    build:
        name: Submit Gradle Dependencies
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Gradle Dependency Submission
              uses: mikepenz/gradle-dependency-submission@v0.9.0
              with:
                  gradle-project-path: 'gradle-example'
                  gradle-build-module: |-
                      :sdks:android:sdk
                      :sdks:android:test-app
