name: 'Tests (TS)'
on:
    push:
        branches:
            - main
        paths:
            - 'frontend/**'
            - 'gen/ts/**'
            - 'services/openai-connector/**'
            - 'services/cohere-connector/**'
            - 'shared/ts/**'
    pull_request:
        branches:
            - main
        paths:
            - 'frontend/**'
            - 'gen/ts/**'
            - 'services/openai-connector/**'
            - 'services/cohere-connector/**'
            - 'shared/ts/**'
env:
    NODE_OPTIONS: '--max_old_space_size=4096'
    DEEPSOURCE_DSN: ${{secrets.DEEPSOURCE_DSN}}
jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 21
            - name: Install PNPM
              uses: pnpm/action-setup@v2.4.0
              id: pnpm-install
              with:
                  version: 8
                  run_install: false
            - name: Setup PNPM Cache
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
            - name: Load Cached Dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
            - name: Install Node dependencies
              run: pnpm install -r
            - name: Download the DeepSource CLI
              run: curl https://deepsource.io/cli | sh
            - name: Test
              run: pnpm run test:coverage
            - name: Upload Coverage Report
              run: ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/cobertura-coverage.xml
