name: 'Tests (Android)'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        paths:
            - '*.gradle.kts'
            - 'gradle.properties'
            - 'gradle/**'
            - 'sdks/android/**'
env:
    DEEPSOURCE_DSN: ${{secrets.DEEPSOURCE_DSN}}
jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: gradle
            - name: Download the DeepSource CLI
              run: curl https://deepsource.io/cli | sh
            - name: Enable gradlew execution
              run: chmod +x gradlew
            - name: Test
              run: ./gradlew koverXmlReportRelease
            - name: Upload Coverage Report
              run: ./bin/deepsource report --analyzer test-coverage --key kotlin --value-file sdks/android/sdk/build/reports/kover/reportRelease.xml
