name: 'Validate'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    validate:
        if: github.ref_name != 'development' && github.ref_name != 'production'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 21
            - name: Install PNPM
              uses: pnpm/action-setup@v2.4.0
              id: pnpm-install
              with:
                  version: 8
                  run_install: false
            - name: Setup PNPM Cache
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
            - name: Load Cached Node Dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
            - name: Install Node dependencies
              run: pnpm install -r
            - name: Setup Golang
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21'
            - name: Load Cached Golang Dependencies
              id: cached-go-dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: go-${{ inputs.go_version }}-v1.0-${{ hashFiles('**/go.sum') }}
            - name: Install Golang dependencies
              shell: bash
              run: go get -v -t ./...
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'
            - name: Install Pre-Commit
              run: python -m pip install pre-commit && pre-commit install
            - name: Load Cached Pre-Commit Dependencies
              id: cached-pre-commit-dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pre-commit/
                  key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
            - name: Lint
              run: pre-commit run --show-diff-on-failure --color=always --all-files
